### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-speedy-plugin#10]
Hello.
OCMS 2.2.32, Speedy version 1.0.8.
Just running the usual composer update and getting this error (on local windows machine and hosted linux).
Any ideas? Thanks.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires offline/speedy-plugin ^1.0, found offline/speedy-plugin[v1.0.8] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
```

**Comment by tobias-kuendig** [comment]
The plugin's package is called `offline/oc-speedy-plugin` (note the `oc-` prefix).

Try uninstalling `offline/speedy-plugin` and run `composer require offline/oc-speedy-plugin` again to install the right package.
